---

- block:

    - name: postgresql user
      postgresql_user:
        name: "{{terminfrontend_db_user}}"
        password: "{{terminfrontend_db_pass}}"

    - name: postgresql database
      postgresql_db:
        name: "{{terminfrontend_db_name}}"
        owner: "{{terminfrontend_db_user}}"

  become: true
  become_user: postgres
