- name: debian package requirements
  apt:
    pkg:
      # PostgreSQL
      - postgresql
      - libpq-dev
      - ssl-cert
      # django
      - python3
      - python3-pip
      - python3-dev
      - python3-psycopg2
      - python3-setuptools
      - build-essential
      - libxml2-dev
      - libxslt1-dev
      - libffi-dev
      - libpq-dev
      - libssl-dev
      - zlib1g-dev
      # uwsgi
      - uwsgi
      - uwsgi-plugin-python3
      # ansible
      - git
      - python-psycopg2
      - npm

- name: set correct permissions for /etc/ssl/private
  file:
    path: /etc/ssl/private
    mode: 0750
    owner: root
    group: ssl-cert

- name: install less from npm
  npm:
    name: less
    global: yes

- name: link less to fix weird behavior of django
  file:
    src: /usr/local/bin/lessc
    dest: /usr/bin/lessc
    state: link

- name: terminfrontend user user
  user:
    name: terminfrontend
    system: yes
    home: /var/lib/terminfrontend

- name: terminfrontend home directory
  file:
    path: /var/lib/terminfrontend
    mode: u=rwx,g=rx,o=
    owner: terminfrontend
    group: terminfrontend
    state: directory

- name: python3env bin directory
  file:
    path: /opt/python3env/bin
    state: directory

- name: python3env binary link
  file:
    src: /usr/bin/python3
    dest: /opt/python3env/bin/python
    state: link
